wandb_version: 1

batch_size:
  value: 64
bc:
  value: 0
common_layers:
  value: 2
common_neurons:
  value: 32
ent_coef:
  value: 1.0e-05
gae_lambda:
  value: 0.95
learning_rate:
  value: 0.0003
n_epochs:
  value: 10
n_steps:
  value: 2048
n_years:
  value: 2000
pi_layers:
  value: 0
pi_neurons:
  value: 0
seed:
  value: 2
vf_layers:
  value: 0
vf_neurons:
  value: 0
