method: grid
metric:
  name: return
  goal: maximize
parameters:
    learning_rate:
        values: [3e-4]
    n_steps:
      values: [2048]
    batch_size:
      values: [64]
    n_epochs:
      values: [10]
    gae_lambda:
      values: [0.95]
    ent_coef:
      values: [1e-5]
    pi_layers:
      values: [0]
    pi_neurons:
      values: [0]
    vf_layers:
      values: [0]
    vf_neurons:
      values: [0]
    common_neurons:
      values: [32]
    common_layers:
      values: [2]
    seed:
      values: [0, 1, 2, 3]
    n_years:
      values: [2000]
    bc:
      values: [0]
