wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True]'
_last_obs:
  desc: null
  value: "[[1. 0.]\n [1. 0.]\n [1. 0.]\n [1. 0.]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f67d5980dc0>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 106000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1652108574
    t:
      1:
      - 1
      - 55
      3:
      - 22
      - 35
      4: 3.8.13
      5: 0.12.16
      8:
      - 5
      - 9
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(11)
algo:
  desc: null
  value: PPO
batch_size:
  desc: null
  value: 64
bc:
  desc: null
  value: 0
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f67d5984af0>
clip_range_vf:
  desc: null
  value: None
common_layers:
  desc: null
  value: 2
common_neurons:
  desc: null
  value: 32
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: 1.0e-05
env:
  desc: null
  value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at
    0x7f67d59d8250>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0003
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f67d681ff70>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 4
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 2048
n_years:
  desc: null
  value: 2000
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: Box([-10. -10.], [10. 10.], (2,), float32)
pi_layers:
  desc: null
  value: 0
pi_neurons:
  desc: null
  value: 0
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n  \
    \  (shared_net): Sequential(\n      (0): Linear(in_features=2, out_features=32,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=32, out_features=32,\
    \ bias=True)\n      (3): Tanh()\n    )\n    (policy_net): Sequential()\n    (value_net):\
    \ Sequential()\n  )\n  (action_net): Linear(in_features=32, out_features=11, bias=True)\n\
    \  (value_net): Linear(in_features=32, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': [32, 32]}'
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f67d59d8970>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
start_time:
  desc: null
  value: 1652108583.2848496
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: ./runs/x103ukav
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 0
vf_coef:
  desc: null
  value: 0.5
vf_layers:
  desc: null
  value: 0
vf_neurons:
  desc: null
  value: 0
